### ISSUE TITLE
Inverted inline menu items in bots

### ISSUE THREAD

**Issue by noxonsu** [toshiapp/toshi-ios-client#204]
Inverted menu when many menu items

![084131fe44 1](https://cloud.githubusercontent.com/assets/2914674/25565485/f3ef2334-2dc7-11e7-9524-8c3f4096ddd8.jpg)

**Comment by Elland** [comment]
@roberthein Will this be addressed by the new chat UI, or do we need to fix this separately?

**Comment by roberthein** [comment]
@Elland This will be addressed in the new chat-ui but depending on the impact we might want to fix this separately. What do you think?

**Comment by Elland** [comment]
I'm of the opinion that bots shouldn't have that many pre-defined options, too clunky. I'm fine waiting on it. 👍

**Comment by roberthein** [comment]
👍

**Comment by noxonsu** [comment]
many use-cases miss if you have 6 items limit:

-Select your country
-Select your language
-Select payment method
-Month of birth
-Any categories 

In my bot  users can make sport prediction. I have 80% coding done, but this bug makes the release impossible :(

**Comment by Elland** [comment]
@noxonsu Thanks for the feedback! A few things tho:

1. Having a web style huge scrollable picker can easily become unfeasible, and really hard to make it accessible.
2. You can ask for the user's preferred language by using a [SOFA:InitRequest](https://github.com/sofaprotocol/sofa-spec). It's one of the fields.
3. Selecting country and date of birth could easily be done by regular typed input.
4. If you have more than 6 payment methods, I can assume that you have a few that could be grouped together? Visa/Master/AmEx could be grouped under credit cards, for example.

Now for assorted categories, you might need to get a bit creative. If the list is really large, you might want to break it down into subcategories? Maybe list them to the user as a regular message and have them type it in?

I hope this helps. Great design often comes from the constraints, not from freedom. 👍

**Comment by noxonsu** [comment]
Is this your principled position? If i make small pull request with fixed this bug, can you approve?

**Comment by Elland** [comment]
> If i make pull request with bugfix, can you approve?

Sure! 👍

**Comment by yuliaveres** [comment]
fixed
