### ISSUE TITLE
Wrong table insets while keyboard is shown

### ISSUE THREAD

**Issue by yuliaveres** [toshiapp/toshi-ios-client#221]
(May be consider using some pod, like TPKeyboardAvoiding, etc?) ? 

There are 2 more items in the bottom but not able to scroll to them.
![img_5800](https://cloud.githubusercontent.com/assets/27722554/25706374/90599dec-30e0-11e7-96ca-69661ed5a644.PNG)

**Comment by Elland** [comment]
@yuliaveres still an issue? If so can you  look into it?

**Comment by yuliaveres** [comment]
will do @Elland

**Comment by yuliaveres** [comment]
fixed
