### ISSUE TITLE
User, balance and contacts wiped out

### ISSUE THREAD

**Issue by dkofodimos** [toshiapp/toshi-ios-client#224]
Team: user @dkof. I opened the app to find I have no balance (had 70 usd) and the settings now show a random user @user67645. I restart the app, now it shows a different random user @64253. All my contacts have been wiped out but not my messages.

**Comment by Elland** [comment]
@dkofodimos I see your user still exists on our backend, and can still see it in the app. From the looks of it, it sounds like you signed out of the app without securing your account first.

If that is indeed the case, there's nothing we can really do. Without your 12 word passphrase, it's impossible to recover an account.

**Comment by Idealist42** [comment]
This same issue happened to me.  Balance is now 0, all contacts are gone.

I never signed out of the app.

I'm also no longer seeing adBot messages, although I'm getting iOS notifications like I'm getting them.  If I try sending messages to the bot I never get a reply.

**Comment by dkofodimos** [comment]
@Elland, I did secure my account. I do have the 12 word phrase. And like the other user that has the same issue,I never signed out of the app. It just happened. Now I am user @87980 :) . next time I load the app I will be a different number. The only workaround is to delete the app from my iphone and re-download it. Then I can log in as @dkof again. BUT it will happen again (I tried that as well). Just out of the blue @dkof will disappear

**Comment by dkofodimos** [comment]
@Elland. It is getting trickier now. I just deleted the app from my iphone. I downloaded it again, I open it and it just logs me in to a random user. As I write it is @user99850. It is asking no password at all. I do not have the opportunity to ever say: "I am @dkof, I want ro login"

**Comment by Elland** [comment]
@dkofodimos 

> next time I load the app I will be a different number

Hmm, looks like something is wrong with either the user persistency or the user creation check. Thanks, that's good information!

> I downloaded it again, I open it and it just logs me in to a random user. 

That's by design. The first launch experience is a newly created user that you can claim. If you sign out, you should get the prompt to restore your account.

As you can imagine, a bug of this nature is hard to trace, for such a complex app, but it's our top priority. 👌 Thanks for the info.

**Comment by Elland** [comment]
@Idealist42 Seems to be the exact same behaviour, where your user will not persist between launches. We're looking into it!

**Comment by isaac-art** [comment]
I've just updated version 1.1.3 that just came up on the App Store and the same has happend with balance at 0 and recent chats all gone. 
I tested asking tokenbot for money and it sends a small amount but I'm still at 0.

**Comment by dkofodimos** [comment]
Issue is still there for me as well (have a 2nd user with username @sofopo)

**Comment by Elland** [comment]
@isaac-art @dkofodimos have you tried deleting and re-installing?

**Comment by isaac-art** [comment]
http://developers.tokenbrowser.com/page/migrating-your-token-wallet has worked for me to get my balance back. But bots i've interacted with like TokenBot still send to the old address. Not a big deal though.

**Comment by Elland** [comment]
This should be working on. Will forward this to the TokenBot developers.

**Comment by yuliaveres** [comment]
@dkofodimos is the case working for you now ?
