### ISSUE TITLE
Margins in home/browse icons when title is too long.

### ISSUE THREAD

**Issue by abarmat** [toshiapp/toshi-ios-client#287]
When the title of a bot is two lines the rating stars lose the padding and it's too close to the next app. Maybe it's better to use a slideshow and when you open the category you see the results as a listview.

![rating](https://user-images.githubusercontent.com/140773/27043361-4a06190c-4f70-11e7-9b88-5c11b9cb6d4f.JPG)

**Comment by Elland** [comment]
Thanks for the report @abarmat ! We've redesigned that screen, implementation will be coming shortly. 💪🏽

**Comment by yuliaveres** [comment]
fixed along with new design implementation
