### ISSUE TITLE
Performance degradation with long chats

### ISSUE THREAD

**Issue by carumusan** [toshiapp/toshi-ios-client#380]
The longer the chat logs for an app get the slower the messaging seems to get. I've noticed this is previous versions but it's still present in version 1.2.4. I'm using an iPhone 6 and 7 and it's more obvious on the 6 but present on both.

Symptoms are:

1. Takes multiple seconds to load chat logs on first open
2. Bot sends a message but the iOS app takes a long time to display
3. Approving a payment will may the "payment sent" sound multiple times (pretty strange)
4. Sounds are played multiple times for other notifications
5. The chat messages will squish up together for a few seconds before displaying the new message
6. Toshi becomes unresponsive for 10+ seconds on receiving a new message.

If I uninstall and reinstall Toshi the messaging becomes much faster again which is the only workaround I currently know of. It's frustrating to use currently with these issues.

**Comment by faymontage** [comment]
Thanks for the report! v1.2.5 has just released with major upgrades to the chat, including performance. Would you be able to let us know if it resolves your issue once you've had a chance to try it out?

**Comment by calummaciver** [comment]
It does not appear to have resolved this particular issue, although I do notice the UI differences. 

Setting up a performance test case with 100, 250, 500 messages and payments back and forth should provide proof of what I'm reporting and would be useful for regression testing in future.

**Comment by yuliaveres** [comment]
@carumusan again, significant chat related improvements were released. would you give a short feedback how does it work for you ?

**Comment by carumusan** [comment]
@yuliaveres Working much better now. Makes it a lot easier to test on iPhone, thank you for fixing.

**Comment by yuliaveres** [comment]
Thx for feedback. closing the issue
