### ISSUE TITLE
SignalServiceKit moving

### ISSUE THREAD

**Issue by michaelkirk** [toshiapp/toshi-ios-client#387]
Hi, sorry if this isn't the best place for this, but I noticed that you were using SignalServiceKit, and I wanted to let you know that we've moved the repository into the primary Signal-iOS repository. You can read more about that here: https://github.com/WhisperSystems/Signal-iOS/pull/2341

I also noticed that you've made some modifications - looking briefly, at least some of them look like good candidates for upstream. Could I convince you to submit those PR's and hopefully get you back on upstream?

**Comment by faymontage** [comment]
@michaelkirk Thanks for the heads up! We'll get on the #2341 change in the coming week 🚀
