### ISSUE TITLE
Visual glitch and loss of state when returning from a user/bot back to the browse screen.

### ISSUE THREAD

**Issue by Elland** [toshiapp/toshi-ios-client#455]
Steps to reproduce:
1. Go to `browse`.
2. Scroll one of the sections horizontally.
3. Select a user/bot.
4. Use the screen edge back gesture to interactively show the browse screen again.

Here it branches out, two glitches are visible. If you hold the transition and don't allow it to finish, you will see this:

![screen shot 2017-08-31 at 10 48 58](https://user-images.githubusercontent.com/54423/29914777-085d9878-8e3a-11e7-8e75-e466e5eef32e.png)

Upon release, it behaves the same as just hitting the back button: lost of state. Instead of having the same scroll position you had before, now every section is back at 0.

**Comment by Elland** [comment]
@yuliaveres was this fixed?

**Comment by yuliaveres** [comment]
yes @Elland  it was.

**Comment by Elland** [comment]
🙌🏽
