### ISSUE TITLE
Can't build the project 

### ISSUE THREAD

**Issue by iWeslie** [toshiapp/toshi-ios-client#482]
I am using `Xcode9` to build the project, this may not cause the build failed.    
It report an error:    
```ld: warning: directory not found for option '-F/Users/weslie/Desktop/XCode/ProjectForReference/Collection/Communication/toshi-ios-client/Token'
ld: /Users/weslie/Desktop/XCode/ProjectForReference/Collection/Communication/toshi-ios-client/Carthage/Build/iOS/BouncyLayout.framework/BouncyLayout compiled with older version of Swift language (3.0) than previous files (4.0) file '/Users/weslie/Desktop/XCode/ProjectForReference/Collection/Communication/toshi-ios-client/Carthage/Build/iOS/BouncyLayout.framework/BouncyLayout' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
    
It says could not find the `Token` in the directory. 
How can I solve the strange error?

**Comment by heumn** [comment]
This looks like an error when compiling BouncyLayout. As I read it it sates that you are compiling with Swift 3, while the previous framework was compiled with Swift 4 that is not backwards compatible with Swift 3 🤔

**Comment by yuliaveres** [comment]
should be compiled with swift4
