### ISSUE TITLE
Can’t refuse payment request

### ISSUE THREAD

**Issue by TacoByte** [toshiapp/toshi-ios-client#515]
Somebody sent me a payment request
Clicking on “refuse” doesn’t do anything, the buttons stay there

**Comment by Graeme-Code** [comment]
![wechatimg206](https://user-images.githubusercontent.com/7915365/31052674-e6cf75b8-a68b-11e7-89d9-ff58c3b548c6.jpeg)

**Comment by faymontage** [comment]
Thanks for reporting! Fixed in 15bc7998672d20f1283ea3809d015923d2d04f4c
