### ISSUE TITLE
Positive Local Currency with 0 ETH 

### ISSUE THREAD

**Issue by Graeme-Code** [toshiapp/toshi-ios-client#517]
After selecting a new local currency (South African Rands), the local currency amount shows a positive balance of R0.03 with a ETH balance of 0. 
Steps to reproduce: 
1. Create New Account on Toshi  App version 1.2.10.99. 
2. Me->Local Currency ->Select South African Rand (ZAR)
3. See a positive local currency of R0.03 with a 0 ETH balance. 

![wechatimg200](https://user-images.githubusercontent.com/7915365/31044939-8e691634-a5d9-11e7-9493-bdd2fd163bcb.jpeg)

**Comment by roberthein** [comment]
We have not been able to reproduce this until now. Do you still have this issue with the latest version?

**Comment by Graeme-Code** [comment]
Hi, 
Updating to latest version of the application solves the problem. I spoke to another user who had the same issue. Root cause was having a positive balance on the testnet version of the application, then upgrading to main-net.

**Comment by designatednerd** [comment]
@Graeme-Code Thanks for letting us know - we'll close this issue out and if you ever see something like this again, please let us know!
