### ISSUE TITLE
iOS screenshots with low resolution when expanded 

### ISSUE THREAD

**Issue by Graeme-Code** [toshiapp/toshi-ios-client#518]
When screenshots are sent from iOS user to iOS user, the screenshots when expanded have low resolution. 
Version 1.2.10.99
iOS 10.3.3 

![wechatimg214](https://user-images.githubusercontent.com/7915365/31052656-510a3aae-a68b-11e7-80c8-8a059bde4b20.jpeg)

**Comment by yuliaveres** [comment]
fixed in v1.2.11
