### ISSUE TITLE
Typo - Token instead of Toshi on Favorites Page

### ISSUE THREAD

**Issue by Graeme-Code** [toshiapp/toshi-ios-client#519]
iOS 10.3.3 
Toshi 1.2.10.99 

Test description "You can invite friends to join Token"
![wechatimg215](https://user-images.githubusercontent.com/7915365/31052699-58b70100-a68c-11e7-8774-4f14207d408d.jpeg)

**Comment by faymontage** [comment]
Fixed in 62ac903ff48c2e67da4617aa8264d7fb0946ad69
