### ISSUE TITLE
Cannot subscribe to AdBot

### ISSUE THREAD

**Issue by mrcoles** [toshiapp/toshi-ios-client#536]
When I chat with AdBot in Toshi, it asks me to Subscribe, but no actionable button appears. I get actionable buttons with other Toshi bots, just not the AdBot.

App version: 1.2.11.101
iPhone 8
OS 11.0.2

I even tried:

1. Independently typing in and submitting "Subscribe", "Subscribe 📩”, “Subscribe📥", “Hi”, etc.
2. Killing the app, re-opening and trying
3. Uninstalling the app, re-opening and trying

![img_2751](https://user-images.githubusercontent.com/136651/31404283-934caa74-adc9-11e7-985e-4e601d887e62.PNG)

**Comment by tristan** [comment]
This was a bug in the bot itself. It was reported to the bot owner and is now fixed.
