### ISSUE TITLE
Debug Linking error while building locally

### ISSUE THREAD

**Issue by sogoiii** [toshiapp/toshi-ios-client#804]
I am trying to build the toshi app locally. But I run into a linking error. 

1. I installed marathon as per the instructions
2. I opend xcodeproj in xcode
3. I changed the signer to my own apple developer account
4. I selected Iphone X 11.3 as the selected device. 

The result is the following:
![toshi_compiling_error](https://user-images.githubusercontent.com/1075040/38356633-37508f52-38fb-11e8-94d6-d9eaca766336.jpeg)

Laptop:
OSX 10.13.3
Xcode 9.3

I suspect the build instructions is missing a step or two.

**Comment by Elland** [comment]
> I opend xcodeproj in xcode


You should've opened the `Token.xcworkspace` 👍 Hope this solves it.

**Comment by sogoiii** [comment]
@Elland Yup, that went a lot further! I get the following error, but I feel better. ill close this ticket

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/.../Library/Developer/CoreSimulator/Devices/57C71AA2-7BEA-46C9-9722-5ACF678714B2/data/Containers/Bundle/Application/01F17E16-3472-414C-9BAC-4CD74634E48B/Toshi.app/Frameworks/Reachability.framework/Reachability
  Reason: Incompatible library version: Reachability requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0
```

**Comment by Elland** [comment]
Which Xcode version are you using?

**Comment by sogoiii** [comment]
I'm on Xcode 9.3

**Comment by Elland** [comment]
Oh, code and dependencies are still on Xcode 9.2. You'll need to use that for now.

**Comment by sogoiii** [comment]
@Elland So I am not an iso developer, so pardon my ignorance. But how would I use Xcode 9.2 instead of Xcode 9.3? Do you mean that i need to change my toolchain to be swift 4.0.3? instead of 4.1? 

I just did `carthage update` and i see some of the dependencies being installed.

**Comment by Elland** [comment]
I mean you'll need to have Xcode 9.2 installed. I didn't check if updating carthage dependencies is enough. 🤞🏽 Let us know.

**Comment by designatednerd** [comment]
@sogoiii You can download Xcode 9.2 from the [Apple Developer portal](https://developer.apple.com/download/more/?name=Xcode) (you'll have to sign in with your Apple Developer account first, though).

**Comment by sogoiii** [comment]
@designatednerd Cool, Ill do try that next
