### ISSUE TITLE
Toshi crashed before passphrase is backed up and account get lost

### ISSUE THREAD

**Issue by foxban** [toshiapp/toshi-ios-client#886]
Hi, all

I downloaded and installed the Toshi App (v1.3.2) from the AppStore.

After creating account, I send my eth into it, then I want to backup my Passphrase and click "Me" tab in the bottom, the app crashed.  I reopened the app, it shows me the "Create or Signin" Page.

When I click Create New Account, it crash again, this occurs every time I try.

While try to fix the problem, I upgrade the Toshi from AppStore to 1.3.5.

It still shows me the "Create or Signin" Page after the upgrade, however, it doesn't crash when I click the Create Button and it does create a new account, my previous account is GONE.

Is there anything I can do to get my Account back?

**Comment by yuliaveres** [comment]
probably the account database got corrupted due to rare issue related to the library, we had a few cases previously. But it is always highly recommended to have your account secured / store your passphrase before you send any money there.

**Comment by foxban** [comment]
The app should not allow users to use the address before the passphrase is backed up.

I think the current flow is a SERIOUS product design defect, and should be optimized ASAP.

**Comment by yuliaveres** [comment]
Thanks for the feedback @foxban , we will take this into account !

**Comment by faymontage** [comment]
We're investigating this issue generally - but @foxban I'd like to look into your account specifically as well. Please get in touch at contact@toshi.org with the TX hash and address affected, and I'll take it from there.
